services:
  # Go application that contains the sharding logic
  app:
    build: ./app
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - sharding-net
    # The application only starts after all shards are ready
    depends_on:
      - mongo-shard-0
      - mongo-shard-1
      - mongo-shard-2
      - mongo-shard-3

  # Definition of the 4 MongoDB shards
  mongo-shard-0:
    image: mongo:7.0
    container_name: mongo-shard-0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_0:/data/db
    networks:
      - sharding-net

  mongo-shard-1:
    image: mongo:7.0
    container_name: mongo-shard-1
    ports:
      - "27018:27017"
    volumes:
      - mongo_data_1:/data/db
    networks:
      - sharding-net

  mongo-shard-2:
    image: mongo:7.0
    container_name: mongo-shard-2
    ports:
      - "27019:27017"
    volumes:
      - mongo_data_2:/data/db
    networks:
      - sharding-net

  mongo-shard-3:
    image: mongo:7.0
    container_name: mongo-shard-3
    ports:
      - "27020:27017"
    volumes:
      - mongo_data_3:/data/db
    networks:
      - sharding-net

# Network for the containers to communicate
networks:
  sharding-net:
    driver: bridge

# Volumes to persist the data of each shard
volumes:
  mongo_data_0:
  mongo_data_1:
  mongo_data_2:
  mongo_data_3: